sudo: false
language: ruby
cache: bundler
script: bundle exec rake release_checks
before_install:
- gem update bundler
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.1
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-14.04
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.3.1
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7
    script: bundle exec rake beaker
    services: docker
    sudo: required
notifications:
  email: false
deploy:
  provider: puppetforge
  user: chwilk
  password:
  secure: "qk6rTARdPVMEo00H9QY+rPUSOVBYOj5hGq2Sbp7wqYxCqguy6EI2bSkwviNo9GFJ6sALidG4IfDtyDKT6ok8+Bv8E4yY8FLm9aWZRappaBFCnGWJCG/HfAipzgEKjZvpi+Wg10BS5bng4M7Bc0rG5Z+uoahHa4VlmRr96+aSgk67hXFq7HstAtFYhX1jWlGZEE/ONBuJyN3h7dtId2PHA90VMpBV1KyKdsojIJyyKa+Mtgd3NH+posdgLFx9VPoZWmP1bpcSLNadignsFyFuX4YTkVjY4qD0HbSe/60qoS7BhkgMJI+ciFimjz3ZaQXPbiZxjASqknktQDrrcQcoswYcnlrNXa9/uq9rfXl4kPS15aDQR2wTIqAtaBYrAfcDmgHcp6UEk8DVP5sTgaCBhoaEYL+UEJMYEuavFhRettpUaJT0bto7E2hU+r1aDZj+dIpwIoVMigQmlRgrmRK2yu/uq7zdN/Z5LRouVRX6NKKgI0MD9+1mTcIS6T9F1CI79tUOD8kPNQ+as1X3+jgibXuDeWcJZ7BDaTQ7UHMc9AfujG19sAoc9dROBIbkUy+wLsVVRBZIuqMcPluIk2B8QWYvDGloYGOCs+EvRxoguUG5KGVB47Azu7D1Z69mtf0bQn+lBT+6eHyPg9a4kEvcjbZoUaR6yaRbiRktNGPwdVM="

